# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddadfaacfc534c8135ebc60e0cb0e4f131ddd2d9c0a9cea279a7df34d054b6988687722ffccc14ce5b59ae3dfdd10884c27a1d435495b335eb4cdbdb93973d23

test:
  secret_key_base: d4d97d1a9dc06a8f7fa2e9e458da56dafcde085709379a2ccc502fb389d92a55795d4d34d7a52e513116bc6be4abb050a03416b39a1b64c9d595fcc518fab2e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
